---
### tasks file for dhcpd

# Import Variable
- name: "Include variaveis por OS"
  include_vars: "{{ loop_vars }}"
  loop: "{{ query('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family|lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: "Instalar servidor de DHCP para o {{ ansible_distribution }} versão {{ ansible_distribution_major_version }}"
  package:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  register: dhcp_installed
  notify:
    - Start dhcp-server

- name: "Configura servidor DHCP"
  import_tasks: files.yml
...
