---
### tasks file for iac-ansible-dhcp-server
- name: Define o arquivo de configuracao fixedaddress.conf
  copy: 
    src: fixedaddress.conf 
    dest: /etc/dhcp/fixedaddress.conf 
    owner: root 
    group: root 
    mode: 0644
  when: dhcp_installed|success
  register: fixedconf

- name: Define o arquivo de configuracao dhcpd-vlan1.conf
  template:
    src: dhcpdvlan1.j2
    dest: /etc/dhcp/dhcpd-vlan.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: vlan1conf
  when: fixedconf|success
  
- name: Define o arquivo de configuracao dhcpd-vlan2.conf
  copy: 
    src: dhcpd-vlan2.conf 
    dest: /etc/dhcp/dhcpd-vlan2.conf 
    owner: root 
    group: root 
    mode: 0644
  register: vlan2conf
  when: vlan1conf|success

- name: Define o arquivo de configuracao /etc/dhcp/dhcpd.conf
  when: vlan2conf|success
  template:
    src: dhcpd.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - Restart dhcp-server
...
